### ISSUE TITLE
morefine s500 getting hot

### ISSUE THREAD

**Issue by ran2k** [daliansky/morefine-S500-Hackintosh#11]
Hello,
I followed the guide.
but I have some issues
1.The pc gets hot
2.the fan is noisy

how i can fix this?

**Comment by joker1961** [comment]
Mine is also, CPU70 more degrees Celsius,
There seems to be a gap between the fan and the CPU.
I will be better after I adjust it myself.

**Comment by RebornL** [comment]
> Mine is also, CPU70 more degrees Celsius, There seems to be a gap between the fan and the CPU. I will be better after I adjust it myself.

May I ask you how to adjust the fan?
Into BIOS, I found it was fixed, can't adjust by myself

**Comment by ran2k** [comment]
daliansky help??

**Comment by joker1961** [comment]
> > Mine is also, CPU70 more degrees Celsius, There seems to be a gap between the fan and the CPU. I will be better after I adjust it myself.
> 
> May I ask you how to adjust the fan? Into BIOS, I found it was fixed, can't adjust by myself

I opened my computer case

**Comment by daliansky** [comment]
You can try to turn the chassis 180 degrees clockwise and place it upside down, so that the temperature can be reduced by at least 6-8 degrees. Another method is to consider adding a copper gasket if you feel that there is a gap between the CPU and the cooling fan.
