### ISSUE TITLE
1.8.0 关于CustomMemory的疑惑

### ISSUE THREAD

**Issue by joker1961** [daliansky/morefine-S500-Hackintosh#12]
EFI版本换成1.8.0，一切正常，什么唤醒、双屏统统没问题，谢谢辛苦付出。
不过还有个疑惑，
关于本机内存显示变成64G，机子本身只有16G，
1.机子会变快一点点吗？
2.需要调整EFI适配本机吗？
谢谢！

**Comment by lnzoro** [comment]
最新更新的配置文件已经修复这个问题
