### ISSUE TITLE
S500-10980hk开机黑屏需要重新插入hdmi才亮

### ISSUE THREAD

**Issue by Air9420** [daliansky/morefine-S500-Hackintosh#17]
系统版本:[HeiPG.cn]Install.macOS.Monterey.12.4(21F79).with.OpenCore.0.8.1.and.Clover.r5146.and.FirPE.dmg
efi:morefine S500 Hackintosh EFI v2.1.0
显示器：lg ultrawide

**Comment by Morzorz** [comment]
同问，搞定的了吗伙计？

**Comment by Morzorz** [comment]
搞定了，重置一下nvram ：sudo nvram -c

**Comment by Air9420** [comment]
> 搞定了，重置一下nvram ：sudo nvram -c

抱歉兄弟，没时间去整这个黑果。但还是谢谢你给的方法，我晚点试试，谢谢

**Comment by xpader** [comment]
我到现在一直是 Mac 系统视频全屏就黑屏，要拨了 HDMI 重插才行。
我线是 HDMI 转 DVI 的。。
