### ISSUE TITLE
DP输出没有声音

### ISSUE THREAD

**Issue by zncs520** [daliansky/morefine-S500-Hackintosh#2]
RT,,
DP输出没有声音如何弄呀

**Comment by Ekkone** [comment]
> 

我的也是DP和HDMI输出没有声音，只有自带的3.5mm音频口可以

**Comment by daliansky** [comment]
DP音频输出取决于显示器，也可以试试更换一根DP线材，我家里的一台AOC 2790的DP就一直可以输出音频，可惜显示器不带音箱；但是公司里的DELL 2718Q就无法音频输出。
