### ISSUE TITLE
用这个EFI会导致外接usb磁盘无法识别，磁盘工具上也看不到外界磁盘设备

### ISSUE THREAD

**Issue by Moonjer** [daliansky/morefine-S500-Hackintosh#20]
问题：用这个EFI会导致外接usb磁盘无法识别，磁盘工具上也看不到外界磁盘设备
详细描述：
我是从ventura系统升级到sonoma系统的。不论是ventura或者sonoma系统，替换这个efi都是这样的情况。进入屏幕保护程序后偶尔会能识别，但推出usb设备再插入又无法识别。除了键盘鼠标usb设备正常，只要是移动盘或者优盘都无法识别，exfat格式或者ntfs格式都没用，磁盘工具根本识别不到硬盘。
其他未发现什么问题，注入oclp无线wifi驱动，博通网卡能正常上网。

**Comment by daliansky** [comment]
新版本已经修复了 USB
