### ISSUE TITLE
MacOS 在微信里播放视频号的视频时，全屏视频一会儿会断开视频信号。

### ISSUE THREAD

**Issue by xpader** [daliansky/morefine-S500-Hackintosh#3]
MacOS 的微信中，播放朋友圈的视频号视频，点开视频的全屏，一会儿屏幕视频信号就断开了，耳机还有声音，把视频线拨了后再连上视频信号恢复。

我是 HDMI 转 DVI 的线。

其它网站视频无此问题。

**Comment by xpader** [comment]
该问题后经调研是显示器和线的问题，因为使用的是 HDMI 转 DVI 的线接到一个比较老的 1080P 显示器上，该显示器没有 HDMI 口只能这样，后使用 HDMI 的线直接接到支持 HDMI 的显示器就正常。应该是小兵说的 edid 之类的问题，猜测是全屏触发系统的优化策略或全屏无法满足 60Hz 导致的，只是猜测。

**Comment by daliansky** [comment]
该问题已关闭
