### ISSUE TITLE
BIOS有什么要求嘛？或者使用什么版本？

### ISSUE THREAD

**Issue by fengci** [daliansky/morefine-S500-Hackintosh#4]
您好，问下我的CPU型号是 I9-9980hk

**Comment by daliansky** [comment]
请问刷bios的目的是？

**Comment by fengci** [comment]
![image](https://user-images.githubusercontent.com/13860628/170162868-464def83-31ae-4a84-8cc5-864868c546fc.png)
我bios是这个版本，刷这个EFI会有错误

**Comment by fengci** [comment]
麻烦问下QQ群答案是什么？
