### ISSUE TITLE
关于核显添加属性AAPL,GfxYTile的作用，以及双显示器启动之后花屏的问题。

### ISSUE THREAD

**Issue by liuxuan0218** [daliansky/morefine-S500-Hackintosh#5]
从网络上了解不到AAPL,GfxYTile property的意思和作用，需要大神科普一下，谢谢。@daliansky

另外双显示器启动，都正常点亮，登陆之后十多秒，就会花屏。重开其中一个显示器之后恢复正常。请问小兵哥最新的release EFI解决了之歌问题吗？解决的方法是什么？

**Comment by daliansky** [comment]
新版本已经修复该问题，建议更新使用
