### ISSUE TITLE
双屏的问题

### ISSUE THREAD

**Issue by joker1961** [daliansky/morefine-S500-Hackintosh#6]
在1.6.0之前有一个未发布版本，那个版正常。

6-9-2022的这个版，启动之后，双屏一直反应，但是点不亮。或者点亮之后hdmi的屏幕一直闪，另一个黑的。把其中一个关掉就可以正常启动，再接第二个屏幕就没问题了

**Comment by daliansky** [comment]
能找到你说的那个未知版本吗？我可以比对一下配置文件

**Comment by joker1961** [comment]
[https://1drv.ms/u/s!AsN1MCPAK9q8heVLt948vFE9qVhqQA?e=4DpQOL](url)
https://1drv.ms/u/s!AsN1MCPAK9q8heVLt948vFE9qVhqQA?e=4DpQOL
不知道怎么上传附件，用onedrive分享了

**Comment by daliansky** [comment]
新版本已经修复该问题。
