### ISSUE TITLE
版本1.7.0 进不了系统，自动重启

### ISSUE THREAD

**Issue by joker1961** [daliansky/morefine-S500-Hackintosh#8]
版本1.7.0 进不了系统，自动重启
切换-v模式，一屏代码跑不到一半就重启
不知道是不是特例。

**Comment by xvortex** [comment]
I have the same issue! macOS Monterey 12.3.(1)
immediate reboot, -v very fast - can't pause and check.
Upgraded from EFI v1.5.0

**Comment by lnzoro** [comment]
一样的问题，直接重启，现在再用1.6版本

**Comment by xpader** [comment]
我还是 1.5.0

**Comment by xvortex** [comment]
Here is the -v log before cyclic reboot.
![oc_log](https://user-images.githubusercontent.com/445263/178416576-dd7c9c6d-a30b-4a75-a2e9-da228a7283bb.jpg)

v1.6.0 works fine.

**Comment by xvortex** [comment]
Fixed!
Changed
`            <key>CustomMemory</key>
            <true/>
`
to
`            <key>CustomMemory</key>
            <false/>
`
and it boots normally.

**Comment by RebornL** [comment]
> Fixed! Changed ` <key>CustomMemory</key> <true/>` to ` <key>CustomMemory</key> <false/>` and it boots normally.

good job, bro

**Comment by lnzoro** [comment]
```
<key>CustomMemory</key>
 <true/> 
```
改成
```
<key>CustomMemory</key>
<false/>
```
这个就好了。

**Comment by joker1961** [comment]
> Fixed! Changed ` <key>CustomMemory</key> <true/>` to ` <key>CustomMemory</key> <false/>` and it boots normally.

thanks

**Comment by joker1961** [comment]
> ```
> <key>CustomMemory</key>
>  <true/> 
> ```
> 
> 改成
> 
> ```
> <key>CustomMemory</key>
> <false/>
> ```
> 
> 这个就好了。

thanks
