### ISSUE TITLE
无法读取风扇转速，RPM 显示为 0

### ISSUE THREAD

**Issue by chenhb23** [daliansky/morefine-S500-Hackintosh#9]
s500 风扇声音有点大，bios 自带的 fan control 功能无法调整风扇的默认转速，所以想用 [macs fan control](https://crystalidea.com/macs-fan-control) 调节转速，但无法读取风扇信息。

请问需要怎么操作，或者打什么补丁才能读取风扇信息呢？

efi 版本: [morefine S500 Hackintosh EFI v1.5.0](https://github.com/daliansky/morefine-S500-Hackintosh/releases/tag/v1.5.0)

![IMG_0860](https://user-images.githubusercontent.com/74194963/179121241-a648c80b-0cfd-438f-a01b-174946122268.jpg)

**Comment by daliansky** [comment]
此题截止到目前还无解
